version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/node-clean"
    command: ["mongod", "--quiet"]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mongo-data:
