version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=192.168.1.4

  redis:
    image: redis
    ports:
      - "6379:6379"
