services:
  app:
    build:
      context: .
    container_name: node-app
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6380:6379"

volumes:
  mongodb-data:
